version: '3.6'

services:
  db:
    build: psql/.
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .dev.env
    volumes:
      - db:/var/lib/postgresql/data

  openldap:
    image: bitnami/openldap:latest
    ports:
      - '1389:1389'
      - '1636:1636'
    env_file:
      - .dev.env
    volumes:
      - openldap:/bitnami

volumes:
  db:
  openldap: